name: PHP Linting

on: push

permissions:
  contents: read

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: "Pint"
        uses: aglipanci/laravel-pint-action@latest
        with:
          verboseMode: true
          testMode: true
          useComposer: true
